name: Merge

inputs:
  number:
    description: PR number
    required: false
    type: string
    default: ${{ github.event.pull_request.number }}
  base:
    description: Target branch name
    required: false
    type: string
    default: ${{ github.event.pull_request.base.ref }}
  subject:
    description: Merge commit subject
    required: false
    type: string
    default: ${{ github.event.pull_request.title }}
  body:
    description: Merge commit body
    required: false
    type: string
    default: ${{ github.event.pull_request.body }}
  version-from:
    description: Method of getting the version if not specified
    required: false
    type: choice
    options:
      - 'commit-message'
      - 'pyproject.toml'
      - 'version-file'
    default: 'version-file'
  version-source:
    description: Source containing the version, e.g. path to a file
    required: false
    type: string
    default: ''
  sha-head:
    description: Head SHA hash
    required: false
    type: string
    default: ${{ github.event.pull_request.head.sha }}
  sha-base:
    description: Base SHA hash
    required: false
    type: string
    default: ${{ github.event.pull_request.base.sha }}
  pattern:
    description: RegEx Pattern on what files trigger release
    type: string
    default: ''
  repo:
    description: GitHub repository
    type: string
    default: ${{ github.repository }}
  default-branch:
    description: Default branch name
    required: false
    type: string
    default: ${{ github.event.repository.default_branch }}
  release-candidate:
    description: Release candidate branch name
    required: false
    type: string
    default: 'release-candidate'
  token:
    description: Access token
    required: false
    type: string
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
  - name: Merge
    env:
      GH_TOKEN: ${{ inputs.token }}
      BODY: ${{ inputs.body }}
    shell: bash
    run: |
      gh pr merge \
        ${{ inputs.number }} \
        --repo "${{ inputs.repo }}" \
        --subject "${{ inputs.subject }}" \
        --body "$BODY" \
        --auto \
        ${{ inputs.base == inputs.default-branch
            && '--squash' || '--merge'}} \
        ${{ inputs.base != inputs.default-branch
            && inputs.base != inputs.release-candidate
            && '--delete-branch \' || '' }}
  - name: Create PR
    if: inputs.base
        != inputs.default-branch
    uses: ./.github/actions/pr-create
    with:
      head: ${{ inputs.base  }}
      version-from: ${{ inputs.version-from }}
      version-source: ${{ inputs.version-source }}
      release-candidate-branch: ${{ inputs.release-candidate}}
      default-branch: ${{ inputs.default-branch }}
  - name: Count matching paths
    if: inputs.base == inputs.default-branch && inputs.pattern
    continue-on-error: true
    id: paths
    shell: bash
    env:
      PATTERN: ${{ inputs.pattern }}
    run: |
      MATCHES="$(git diff --name-only \
                  ${{ inputs.sha-base }} \
                  ${{ inputs.sha-head }} \
                | grep -c $PATTERN)"
      echo "$MATCHES"
      echo "matches=${MATCHES/0/}" >> "$GITHUB_OUTPUT"
  - name: GH release
    if: ${{ !inputs.pattern || steps.paths.outputs.matches }}
    uses: lime-actions/gh-release@latest
