name: Update Tags
description: Update Tags based on a version

inputs:
  tag:
    description: Version to be updated
    required: false
    type: string
    default: ''
  message:
    description: Annotated tag message
    required: false
    type: string
    default: ''
  git-name:
    description: Name for the author of the tags
    required: false
    type: string
    default: 'GitHub Actions'
  git-email:
    description: Email for the author of the tags
    required: false
    type: string
    default: 'github-actions@users.noreply.github.com'
  latest-ref:
    description: Name of the reference to the latest-release
    required: false
    type: string
    default: latest

outputs:
  tag:
    description: Tag created
    value: ${{ steps.tag.outputs.tag }}
  message:
    description: Message on the tag
    value: ${{ steps.tag.outputs.message }}

runs:
  using: 'composite'
  steps:
  - name: Update tags
    id: tag
    shell: bash
    env:
      MESSAGE: ${{ inputs.message }}
    run: |
      git config user.name ${{ inputs.git-name }}
      git config user.email ${{ inputs.git-email }}

      TAG=${{ inputs.tag || '$(git log -1 --pretty=format:"%s")'}}

      echo "tag=$TAG" >> "$GITHUB_OUTPUT"
      echo "message=$MESSAGE" >> "$GITHUB_OUTPUT"

      ${{ !inputs.tag && 'MESSAGE="$(git log -1 --pretty=format:"%b")"' }}

      git tag "$TAG" --message="$MESSAGE"
      git tag "${{ inputs.latest-ref }}" --force --message="$MESSAGE"

      while
        TAG=$(sed -nE --expression='s/([^\.]+(\.[^\.]+)*)\.[^\.]+/\1/p' \
              <<< "$TAG")
        [ -n "$TAG" ]
      do
        echo "$TAG"
        git tag "$TAG" --force
      done

      git push origin --tags --force
