name: Merge
run-name: Merging ${{ github.event.pull_request.head.ref }} -> ${{ github.event.pull_request.base.ref }}

on:
  pull_request_review:
    types:
    - submitted
    paths:
    - version.txt

jobs:
  merge:
    if: ${{ github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          action.yaml
          .github/actions/merge/action.yaml
          ${{ github.event.pull_request.base.ref
              != github.event.repository.default_branch
              && 'version.txt
                  .github/actions/pr-create/action.yaml'
              || '' }}
        sparse-checkout-cone-mode: false
    - name: Merge
      uses: ./.github/actions/merge
    - name: Merge back
      if: github.event.pull_request.base.ref
          == github.event.repository.default_branch
      run: |
        git config user.name GitHub Actions
        git config user.email github-actions@users.noreply.github.com
        git checkout release-candidate
        git merge ${{ github.event.pull_request.base.ref }} -X ours
        git push
        git checkout dev
        git merge ${{ github.event.pull_request.base.ref }} -X ours
        git push
