name: Release
description: Creates tag and release based on the commit message
on:
  workflow_call:

jobs:
  release:
    if: github.event.pull_request.base.ref
        == github.event.repository.default_branch
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.base.ref }}
    - name: Create and update tags
      id: tag
      uses: ./.github/actions/update-tags
    - name: Create release and add comment
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release create \
          "${{ steps.tag.outputs.tag }}" \
          --title "${{ steps.tag.outputs.tag }}" \
          --verify-tag \
          --notes-from-tag

        gh pr comment \
          ${{ github.event.pull_request.number }} \
          --body '${{
            format('@{0} Release {1}/releases/tag/{2} published',
                   github.event.pull_request.assignee.name,
                   github.repositoryUrl,
                   steps.tag.outputs.tag) }}'
