name: Update PR title
description: Update PR title with the version of the contents

on:
  pull_request:
    types:
    - opened
    - synchronize
    paths:
    - 'pyproject.toml'

jobs:
  update-pr-title:
    if: ${{ github.event.pull_request.base.ref
            == github.event.repository.default_branch
            ||  github.event.pull_request.base.ref
            == 'release-candidate' }}
    permissions:
       pull-requests: write
       contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Get version
      id: version
      uses: ./
      with:
        from: 'pyproject.toml'
    - name: Format title
      id: title
      run: |
        echo "title=v${{ steps.version.outputs.version }}" \
        >> "$GITHUB_OUTPUT"
    - name: Edit PR
      if: ${{ steps.title.outputs.title != github.event.pull_request.title}}
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh pr edit ${{ github.event.number }} \
          --title  "${{ steps.title.outputs.title }}"
